import os, sys
Import('env')
env = env.Clone()

cpps = Glob("*.cpp")
lib = env.SharedLibrary(target = env["build_lib_path"][0] + "web_engine_toy_dom", 
        source = cpps)

SConscript("test/SConscript")
